#!/bin/sh -e

ok() {
	printf '\033[1;32m ok \033[0m\n'
}

ARG0="$(basename $0)"

usage() {
	printf '%s <service name>\n' "$ARG0"
}

if [ -z "$1" ]
then
	usage
	exit 1
fi

if [ -f "/run/init.d/$1" ]
then
	exit 0
fi

oneshot=
service=
wait=

if [ -x "/etc/init.d/$1/oneshot" ]
then
	oneshot=1
fi

if [ -x "/etc/init.d/$1/run" ]
then
	service=1
fi

if [ -x "/etc/init.d/$1/wait" ]
then
	wait=1
fi

if [ -f "/etc/init.d/$1/deps" ]
then
	PIDs=
	while read dep
	do
    		set +e
		initrun "$dep" #&
		set -e
# 		PIDs="$PIDs$!
# "
	done < "/etc/init.d/$1/deps"
	if [ ! -z "$PIDs" ]
	then
		wait $PIDs
	fi
fi

if [ ! -z "$service" ]
then
	printf 'Starting %-16s' "$1"

	# TODO: supervision and process restarting
	# TODO: handle errors properly
	# TODO: fancy looking logging
	# TODO: logging
	nohup "/etc/init.d/$1/run" >/dev/null &
	PID="$!"
	printf '%s\nstarting\n' "$PID" > "/run/init.d/$1"

	if [ ! -z "$wait" ]
	then
		"/etc/init.d/$1/wait"
	fi

	printf '%s\nstarted\n' "$PID" > "/run/init.d/$1"

	ok
elif [ ! -z "$oneshot" ]
then
	printf 'Running  %-16s' "$1"
	"/etc/init.d/$1/oneshot"
	printf '0\nrun\n' > "/run/init.d/$1"
	ok
fi
