#!/bin/sh
export USER=ella
export HOME=/home/ella

groups="$(id -Gn "$USER" | tr ' ' ':')"
svdir="$HOME/.config/service"

export XDG_RUNTIME_DIR=/run/user/1000

for f in find /dev -type c -perm 600 -user ella -name 'tty*'; do
	if [ ! -d "$XDG_RUNTIME_DIR" ]; then
		mkdir -p "$XDG_RUNTIME_DIR"
		chmod 0700 "$XDG_RUNTIME_DIR"
		chown ella:ella "$XDG_RUNTIME_DIR"
	fi

	case "$f" in
		'/dev/tty6'))
			touch /run/user/1000/graphical
			;;
		*))
			;;
	esac
	if [ ! -f /run/user/1000/running ]; then
		touch /run/user/1000/running
		setsid -d chpst -u "$USER:$groups" runsvdir "$svdir"&
	fi
done
sleep 1
